version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: quotes_db
      MYSQL_USER: quotes_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/quotes_db
      SPRING_DATASOURCE_USERNAME: quotes_user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - db
