version: '3.8'
services:
  tomcat:
    image: tomcat:10.0-jdk17
    ports:
      - "8080:8080"
      - "5005:5005"
    command: "catalina.sh run"
    volumes:
      - "./target:/usr/local/tomcat/webapps"
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"